/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as AuthenticatedMarketplaceApplicationsRouteImport } from './routes/_authenticated/marketplace.applications'
import { Route as AuthenticatedMarketplaceManageRouteImport } from './routes/_authenticated/marketplace.manage'
import { Route as AuthenticatedMarketplaceSavedRouteImport } from './routes/_authenticated/marketplace.saved'
import { Route as CreatorPlatformUsernameRouteImport } from './routes/creator.$platform.$username'
import { Route as MarketplaceCampaignsCampaignIdRouteImport } from './routes/marketplace.campaigns.$campaignId'
import { Route as AuthenticatedMarketplaceManageCampaignIdRouteImport } from './routes/_authenticated/marketplace.manage.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMarketplaceApplicationsRoute =
  AuthenticatedMarketplaceApplicationsRouteImport.update({
    id: '/marketplace/applications',
    path: '/marketplace/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceManageRoute =
  AuthenticatedMarketplaceManageRouteImport.update({
    id: '/marketplace/manage',
    path: '/marketplace/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceSavedRoute =
  AuthenticatedMarketplaceSavedRouteImport.update({
    id: '/marketplace/saved',
    path: '/marketplace/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CreatorPlatformUsernameRoute = CreatorPlatformUsernameRouteImport.update({
  id: '/creator/$platform/$username',
  path: '/creator/$platform/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCampaignsCampaignIdRoute =
  MarketplaceCampaignsCampaignIdRouteImport.update({
    id: '/marketplace/campaigns/$campaignId',
    path: '/marketplace/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketplaceManageCampaignIdRoute =
  AuthenticatedMarketplaceManageCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedMarketplaceManageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/applications': typeof AuthenticatedMarketplaceApplicationsRoute
  '/marketplace/manage': typeof AuthenticatedMarketplaceManageRouteWithChildren
  '/marketplace/saved': typeof AuthenticatedMarketplaceSavedRoute
  '/creator/$platform/$username': typeof CreatorPlatformUsernameRoute
  '/marketplace/campaigns/$campaignId': typeof MarketplaceCampaignsCampaignIdRoute
  '/marketplace/manage/$campaignId': typeof AuthenticatedMarketplaceManageCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/marketplace/applications': typeof AuthenticatedMarketplaceApplicationsRoute
  '/marketplace/manage': typeof AuthenticatedMarketplaceManageRouteWithChildren
  '/marketplace/saved': typeof AuthenticatedMarketplaceSavedRoute
  '/creator/$platform/$username': typeof CreatorPlatformUsernameRoute
  '/marketplace/campaigns/$campaignId': typeof MarketplaceCampaignsCampaignIdRoute
  '/marketplace/manage/$campaignId': typeof AuthenticatedMarketplaceManageCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/_authenticated/marketplace/applications': typeof AuthenticatedMarketplaceApplicationsRoute
  '/_authenticated/marketplace/manage': typeof AuthenticatedMarketplaceManageRouteWithChildren
  '/_authenticated/marketplace/saved': typeof AuthenticatedMarketplaceSavedRoute
  '/creator/$platform/$username': typeof CreatorPlatformUsernameRoute
  '/marketplace/campaigns/$campaignId': typeof MarketplaceCampaignsCampaignIdRoute
  '/_authenticated/marketplace/manage/$campaignId': typeof AuthenticatedMarketplaceManageCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/marketplace/'
    | '/marketplace/applications'
    | '/marketplace/manage'
    | '/marketplace/saved'
    | '/creator/$platform/$username'
    | '/marketplace/campaigns/$campaignId'
    | '/marketplace/manage/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/marketplace/applications'
    | '/marketplace/manage'
    | '/marketplace/saved'
    | '/creator/$platform/$username'
    | '/marketplace/campaigns/$campaignId'
    | '/marketplace/manage/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/marketplace/'
    | '/_authenticated/marketplace/applications'
    | '/_authenticated/marketplace/manage'
    | '/_authenticated/marketplace/saved'
    | '/creator/$platform/$username'
    | '/marketplace/campaigns/$campaignId'
    | '/_authenticated/marketplace/manage/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  CreatorPlatformUsernameRoute: typeof CreatorPlatformUsernameRoute
  MarketplaceCampaignsCampaignIdRoute: typeof MarketplaceCampaignsCampaignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/applications': {
      id: '/_authenticated/marketplace/applications'
      path: '/marketplace/applications'
      fullPath: '/marketplace/applications'
      preLoaderRoute: typeof AuthenticatedMarketplaceApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/manage': {
      id: '/_authenticated/marketplace/manage'
      path: '/marketplace/manage'
      fullPath: '/marketplace/manage'
      preLoaderRoute: typeof AuthenticatedMarketplaceManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/saved': {
      id: '/_authenticated/marketplace/saved'
      path: '/marketplace/saved'
      fullPath: '/marketplace/saved'
      preLoaderRoute: typeof AuthenticatedMarketplaceSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/creator/$platform/$username': {
      id: '/creator/$platform/$username'
      path: '/creator/$platform/$username'
      fullPath: '/creator/$platform/$username'
      preLoaderRoute: typeof CreatorPlatformUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/campaigns/$campaignId': {
      id: '/marketplace/campaigns/$campaignId'
      path: '/marketplace/campaigns/$campaignId'
      fullPath: '/marketplace/campaigns/$campaignId'
      preLoaderRoute: typeof MarketplaceCampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/manage/$campaignId': {
      id: '/_authenticated/marketplace/manage/$campaignId'
      path: '/$campaignId'
      fullPath: '/marketplace/manage/$campaignId'
      preLoaderRoute: typeof AuthenticatedMarketplaceManageCampaignIdRouteImport
      parentRoute: typeof AuthenticatedMarketplaceManageRoute
    }
  }
}

interface AuthenticatedMarketplaceManageRouteChildren {
  AuthenticatedMarketplaceManageCampaignIdRoute: typeof AuthenticatedMarketplaceManageCampaignIdRoute
}

const AuthenticatedMarketplaceManageRouteChildren: AuthenticatedMarketplaceManageRouteChildren =
  {
    AuthenticatedMarketplaceManageCampaignIdRoute:
      AuthenticatedMarketplaceManageCampaignIdRoute,
  }

const AuthenticatedMarketplaceManageRouteWithChildren =
  AuthenticatedMarketplaceManageRoute._addFileChildren(
    AuthenticatedMarketplaceManageRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketplaceApplicationsRoute: typeof AuthenticatedMarketplaceApplicationsRoute
  AuthenticatedMarketplaceManageRoute: typeof AuthenticatedMarketplaceManageRouteWithChildren
  AuthenticatedMarketplaceSavedRoute: typeof AuthenticatedMarketplaceSavedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketplaceApplicationsRoute:
    AuthenticatedMarketplaceApplicationsRoute,
  AuthenticatedMarketplaceManageRoute:
    AuthenticatedMarketplaceManageRouteWithChildren,
  AuthenticatedMarketplaceSavedRoute: AuthenticatedMarketplaceSavedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  CreatorPlatformUsernameRoute: CreatorPlatformUsernameRoute,
  MarketplaceCampaignsCampaignIdRoute: MarketplaceCampaignsCampaignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
